# Generated by Django 4.1.2 on 2022-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_alter_instructor_description_alter_lesson_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=30, null=True),
        ),
    ]
